// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eigen_version
void eigen_version();
RcppExport SEXP _RcppStatGen_eigen_version() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    eigen_version();
    return R_NilValue;
END_RCPP
}
// eigen_scale
Eigen::MatrixXd eigen_scale(Eigen::MatrixXd X0, int verbose);
RcppExport SEXP _RcppStatGen_eigen_scale(SEXP X0SEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_scale(X0, verbose));
    return rcpp_result_gen;
END_RCPP
}
// eigen_scale_naive
Eigen::MatrixXd eigen_scale_naive(Eigen::MatrixXd X0);
RcppExport SEXP _RcppStatGen_eigen_scale_naive(SEXP X0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X0(X0SEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_scale_naive(X0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppStatGen_eigen_version", (DL_FUNC) &_RcppStatGen_eigen_version, 0},
    {"_RcppStatGen_eigen_scale", (DL_FUNC) &_RcppStatGen_eigen_scale, 2},
    {"_RcppStatGen_eigen_scale_naive", (DL_FUNC) &_RcppStatGen_eigen_scale_naive, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppStatGen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
