# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
eigen_version <- function() {
    invisible(.Call(`_RcppStatGen_eigen_version`))
}

#' @export
eigen_scale <- function(X0, verbose = 0L) {
    .Call(`_RcppStatGen_eigen_scale`, X0, verbose)
}

#' @export
eigen_scale_inplace <- function(X) {
    invisible(.Call(`_RcppStatGen_eigen_scale_inplace`, X))
}

#' @export
eigen_scale_naive <- function(X0) {
    .Call(`_RcppStatGen_eigen_scale_naive`, X0)
}

#' @export
eigen_scale_template <- function(X, verbose = 0L) {
    .Call(`_RcppStatGen_eigen_scale_template`, X, verbose)
}

#' @export
eigen_qr_keep <- function(X, tol = 1e-7, verbose = 0L) {
    .Call(`_RcppStatGen_eigen_qr_keep`, X, tol, verbose)
}

#' @export
eigen_qri_keep <- function(X0, cols_selected, tol = 1e-7, verbose = 0L) {
    .Call(`_RcppStatGen_eigen_qri_keep`, X0, cols_selected, tol, verbose)
}

#' @export
eigen_print_sum <- function(X) {
    invisible(.Call(`_RcppStatGen_eigen_print_sum`, X))
}

